<?php

require_once dirname(__FILE__) . '/../../../shared/ez_sql_core.php';
require_once dirname(__FILE__) . '/../../../oracle8_9/ez_sql_oracle8_9.php';

/**
 * Test class for ezSQL_oracle8_9.
 * Generated by PHPUnit on 2012-04-02 at 00:24:07.
 */
class ezSQL_oracle8_9Test extends PHPUnit_Framework_TestCase {

    /**
     * @var ezSQL_oracle8_9
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ezSQL_oracle8_9;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ezSQL_oracle8_9::connect
     * @todo Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::quick_connect
     * @todo Implement testQuick_connect().
     */
    public function testQuick_connect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::select
     * @todo Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::escape
     * @todo Implement testEscape().
     */
    public function testEscape() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::sysdate
     * @todo Implement testSysdate().
     */
    public function testSysdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::is_equal_str
     * @todo Implement testIs_equal_str().
     */
    public function testIs_equal_str() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::is_equal_int
     * @todo Implement testIs_equal_int().
     */
    public function testIs_equal_int() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::insert_id
     * @todo Implement testInsert_id().
     */
    public function testInsert_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::nextVal
     * @todo Implement testNextVal().
     */
    public function testNextVal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::query
     * @todo Implement testQuery().
     */
    public function testQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::disconnect
     * @todo Implement testDisconnect().
     */
    public function testDisconnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ezSQL_oracle8_9::getDBName
     * @todo Implement testGetDBName().
     */
    public function testGetDBName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
